---
title: "stats510_2"
author: "Christoper Chan"
date: "December 4, 2018"
output: 
  github_document:
    pandoc_args: --webtex

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##2.1 Moving Average Models
* 1st order MA(1) = $x_t = \mu + w_t + \theta_{1}w_{t-1}$
    + qth order MA($q$) = $x_t = \mu + w_t + \theta_{1}w_{t-1} + \theta_{2}w_{t-2} + ... + \theta_{q}w_{t-q}$
    + Properties:
        - Mean $E(x_t) = \mu$
        - $Var(x_t) = \sigma^2_w(1 + \theta^2_1)$
        - ACF = $$rho_1 = \frac{\theta_1}{1 + \theta^2_1}$$ and $\rho_h = 0$ for $h\geq2$
            * For MA(q): nonzero AC for first q lags and $AC = 0$ for $lags\legq$
            
    + Shows $y_t$ correlated with $y_{t-1}$

```{r, warning=FALSE, message=FALSE}
library(tidyverse)
library(zoo)
```
            
```{r}
ma2 <- ARMAacf(ma=c(0.5, 0.3), lag.max=10)
ma2
```

```{r}
lags <- data.frame(0:10)
s <- cbind(ma2, lags, make.row.names = T)
print(s)
ggplot(s, aes(lags, ma2)) +
  geom_point() +
  geom_line() +
  ylab('r') +
  ggtitle('ACF for MA(2) with theta1 = 0.5,theta2=0.3')

```

```{r}
xc <- arima.sim(n=150, list(ma=c(0.5, 0.3)))
x <- as_tibble(xc + 10)

plot(x, type='b')
```

```{r}
autoplot.zoo(x, geom = 'point') + 
  geom_line() +
  ylab('Time')
  ggtitle('Simulated MA(2) Series')
```

```{r}
acf(x, xlim = c(1,10), main = 'ACF for simulated MA(2) data')
```


##2.2 Partial Autocorrelation Function (PACF)
* qth order PACF = $$\frac{Cov(x_t, x_{t-q}|x_{t-1},... x_{t-q-1})}{\sqrt{Var(x_t|x_{t-1},... x_{t-q-1})Var(x_{t-q}|x_{t-1},... x_{t-q-1})}}$$
    + For AR model PACF is order of the model

##2.3 Notational conventions


























